In [4]:
# Soal 1 Function
list1 = [1,3,4,5]
list2 = [22,17,19,20,14]
list3 = [1,3,5]
list4 = [2,4,6]

def convertAngka(fn, collection) :
    newCollection = []
    for item in collection :
       newCollection.append(fn(item))
    print(newCollection)

def sebutAngka(angka):
    if angka % 2 == 0 :
        return "Genap"
    else :
        return "Ganjil"


convertAngka(sebutAngka, list1)
convertAngka(sebutAngka, list2)
convertAngka(sebutAngka, list3)
convertAngka(sebutAngka, list4)

['Ganjil', 'Ganjil', 'Genap', 'Ganjil']
['Genap', 'Ganjil', 'Ganjil', 'Genap', 'Genap']
['Ganjil', 'Ganjil', 'Ganjil']
['Genap', 'Genap', 'Genap']


In [68]:
# Soal 2 Function
list2 = [9100000, 9800000, 9500000, 10300000, 9300000]
standard = 9500000

def isBelowStandard(angka) :
    return angka >= standard

hasilFilter = filter(isBelowStandard, list2)

hasilFilterList = list(hasilFilter)

print(hasilFilterList)



[9800000, 9500000, 10300000]


In [ ]:
# Soal 3
# Soal 3

listBuah = [["Apel", 20, 10000],["Jeruk", 15, 15000],["Anggur", 25, 20000]] 
listCart = []

def menu0() :
    print("Selamat Datang di Pasar Buah")
    print("\nList Menu :")
    print("1. Menampilkan Daftar Buah")
    print("2. Menambah Buah")
    print("3. Menghapus Buah")
    print("4. Membeli Buah")
    print("5. Exit Program")
    selectedMenu = input("Masukkan angka Menu yang ingin dijalankan : ")
    if selectedMenu == "1" :
        menu1()
        menu0()
    elif selectedMenu == "2" :
        menu2()
        menu1()
    elif selectedMenu == "3" :
        menu3()
    elif selectedMenu == "4" :
        menu4()

def menu1() : 
    print("Daftar Buah\n")
    print("{:<8}| {:<10}| {:<10}| {:<10}".format("Index", "Nama", "Stock", "Harga"))
    for i in range(len(listBuah)) :
        print("{:<8}| {:<10}| {:<10}| {:<10}".format(i, listBuah[i][0], listBuah[i][1], listBuah[i][2]))
   

def menu2() : 
    namaBuah = input("{:<20}: ".format("Masukkan Nama Buah"))
    stokBuah = int(input("{:<20}: ".format("Masukkan Stock Buah")))
    hargaBuah = int(input("{:<20}: ".format("Masukkan Harga Buah")))
    buahBaru = []
    buahBaru.append(namaBuah)
    buahBaru.append(stokBuah)
    buahBaru.append(hargaBuah)
    listBuah.append(buahBaru)
     

def menu3() : 
    menu1()
    buahHapus = int(input("Masukkan index buah yang ingin dihapus : "))
    del listBuah[buahHapus]
    menu1()
    menu0()

def menu4() : 
    menu1()
    listCart = []
    buy(listCart)

def buy(listCart) :
    indexBeliBuah = int(input("Masukkan index buah yang ingin dibeli : "))
    qtyBeliBuah = int(input("Masukkan jumlah yang ingin dibeli : "))
    selectedBuah = listBuah[indexBeliBuah]
    print(qtyBeliBuah)
    print(selectedBuah[1])
    if qtyBeliBuah > selectedBuah[1] :
        print("Stock tidak cukup, stock {} tinggal {}".format(selectedBuah[0], selectedBuah[1]))
    else :
        buahBaru = []
        buahBaru.append(selectedBuah[0])
        buahBaru.append(selectedBuah[1])
        buahBaru.append(selectedBuah[2])
        buahBaru.append(selectedBuah[1]*selectedBuah[2])
        listCart.append(buahBaru)
    print("Isi Cart :")
    print("{:<10}| {:<10}| {:<10}".format("Nama", "Qty", "Harga"))
    for i in range(len(listCart)) :
        print("{:<10}| {:<10}| {:<10}".format(listCart[i][0], listCart[i][1], listCart[i][2]))
    jawaban = ""
    while(not (jawaban == "ya" or jawaban == "tidak")) :
        jawaban = input("Mau beli yang lain tidak? (ya/tidak) = ")
    if jawaban == "ya" :
        buy(listCart)
    else :
        print("Daftar Belanja :")
        print("{:<10}| {:<10}| {:<10}| {:<10}".format("Nama", "Qty", "Harga", "Total Harga"))
        totalHarga = 0
        for i in range(len(listCart)) :
            print("{:<10}| {:<10}| {:<10}| {:<10}".format(listCart[i][0], listCart[i][1], listCart[i][2], listCart[i][3]))
            totalHarga = totalHarga + listCart[i][3]
        if totalHarga > 0 : 
            print("Total Yang Harus Dibayar = {}".format(totalHarga))
            bayar = int(input("Masukkan jumlah uang : "))
            selisih = bayar - totalHarga
            while(selisih < 0) :
                print("Uang anda kurang sebesar {}".format(selisih * -1))
                bayar = int(input("Masukkan jumlah uang : "))
                selisih = bayar - totalHarga 
            if selisih > 0 : 
                print("Terima kasih")
                print("\nUang kembali anda : {}".format(selisih))
            else :
                print("Terima kasih")
            
menu0() 

In [22]:
# Numpy
import numpy as np

myList = [1,2,3]
np.array(myList)

myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(myList)



array([1, 2, 3])

In [24]:
# Exercise 1
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
arr = np.arange(mulai, selesai)

level2 = 9
arr2 = arr.reshape(3, level2)

level3 = 3
arr3 = arr.reshape(3, level3, level3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
# Exercise 2
n = int(input("Banyak data : "))
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))

arr = np.random.randint(mulai, selesai, n)

level2 = 4
arr2 = arr.reshape(4, level2)
print(arr2)

arr2[:,::-1]



[[48  4 15 37]
 [30 39 18 42]
 [39 38 18 39]
 [28 30  1 34]]


array([[37, 15,  4, 48],
       [42, 18, 39, 30],
       [39, 18, 38, 39],
       [34,  1, 30, 28]])

In [77]:
x = np.ones((10,10))*4
# [a:b, c:d]
# baris (dari sampai), kolom (dari sampai)
x[1:-1,1:-1]=0 
print(x)


[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
