In [19]:
#Soal 1
import numpy as np

mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
arr1 = np.arange(mulai, selesai)
print(arr1)
print("\n")

arr2 = arr1.reshape(3,9)
print(arr2)
print("\n")

arr3 = arr1.reshape(3,3,3)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]




In [21]:
# Soal 2
n = int(input("Banyak data : "))
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))

arr = np.random.randint(mulai, selesai, n)

level2 = 4
arr2 = arr.reshape(4, level2)
print(arr2)

arr2[:,::-1]

[[48 16 25 31]
 [ 5 23 15 14]
 [ 6 22 34 23]
 [21 34 41 49]]


array([[31, 25, 16, 48],
       [14, 15, 23,  5],
       [23, 34, 22,  6],
       [49, 41, 34, 21]])

In [22]:
# Soal 3
x = np.ones((10,10))*4
# [a:b, c:d]
# baris (dari sampai), kolom (dari sampai)
x[1:-1,1:-1]=0 
print(x)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


In [26]:
# Soal 4
import pandas as pd

labels = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
myList = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]

pd.Series(data=myList, index=labels)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

In [85]:
# Soal 5
myList = np.random.randint(1, 5, 100)
sr = pd.Series(data=myList)


# df = pd.DataFrame(sr, columns=["Value"])
# df2 = df.groupby(["Value"])["Value"].count().reset_index(name='Frequency')
# print(df2)
# df2.sort_values("Frequency", ascending=False).head(2)

sr.value_counts().sort_values(ascending=False).head(2)

 


2    29
4    26
dtype: int64

In [86]:
# Soal 6
import seaborn as sns

mpg = sns.load_dataset('mpg')


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [ ]:
mpg.head()

In [88]:
mpg.describe()


origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [ ]:
mpg.describe(include=object)

In [89]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [91]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [102]:
# Soal 7
import seaborn as sns
df = sns.load_dataset('mpg') 

bool1 = pd.isnull(df['horsepower']) 
df2 = df[bool1]
print(df2)

df2.index



      mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl  


Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [115]:
# Soal 8
import seaborn as sns
df = sns.load_dataset('mpg')
byOrigin = df.groupby('origin') 
byOrigin.mean()["horsepower"]


origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

In [118]:
# Soal 9
import seaborn as sns
df = sns.load_dataset('mpg')


def showHorsepower(horsepower, origin) :
    if horsepower < 105 :
        return "lower " + origin
    else :
        return "upper " + origin

df['horse_origin'] = df.apply(lambda x: showHorsepower(x['horsepower'], x['origin']), axis=1)
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

In [129]:
# Soal 10
import seaborn as sns
df = sns.load_dataset('mpg')


byOrigin = df.groupby('origin') 


byOriginMean = byOrigin.mean()['weight'].reset_index(name='mean') 
byOriginStd = byOrigin.std()['weight'].reset_index(name='std')
byOriginSum = byOrigin.sum()['weight'].reset_index(name='sum')
byOriginCount = byOrigin.count()['weight'].reset_index(name='count')
byOriginMin = byOrigin.min()['weight'].reset_index(name='min')
byOriginMax = byOrigin.max()['weight'].reset_index(name='max')

merge1 = pd.merge(byOriginMean, byOriginStd, on="origin")
merge2 = pd.merge(merge1, byOriginSum, on="origin")
merge3 = pd.merge(merge2, byOriginCount, on="origin")
merge4 = pd.merge(merge3, byOriginMin, on="origin")
merge5 = pd.merge(merge4, byOriginMax, on="origin") 

print(merge5)


   origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140
